[package]
name = "tiledb-expr"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
datafusion = { workspace = true }
tiledb-arrow = { workspace = true }
