# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
repos:
  # Autoformat: C and C++ code
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v9.0.0
    hooks:
    -   id: clang-format
        types_or: [c++, c]
