name: "CI ASAN Ubuntu"
on:
  workflow_dispatch:
  push:

jobs:
  asan:
    uses: ./.github/workflows/ci-linux_mac.yml
    with:
      ci_option: ASAN
      matrix_image: macos-latest
      cmake_generator: 'Ninja' # Use Ninja due to performance issues.
      timeout: 120
      bootstrap_args: '--enable-serialization'
      asan: true
      rust: false
